
package semana07.practico;

public class ejercicio01 extends javax.swing.JFrame {
    double ex1[];
    double ex2[];
    double ex3[];
    int pos[];
    double prom[];
    int conta,contap,contd,contex1,x;
    /**
     * Creates new form ejercicio01
     */
    public ejercicio01() {
        initComponents();
        ex1 = new double[50];
        ex2 = new double[50];
        ex3 = new double[50];
        pos = new int[50];
        prom = new double[50];
        conta=0;
        contap=0;
        contd=0;
        contex1=0;
        x=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnroestudiante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btngrabar = new javax.swing.JButton();
        btncalcular = new javax.swing.JButton();
        txtexamen1 = new javax.swing.JTextField();
        txtexamen2 = new javax.swing.JTextField();
        txtexamen3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpromedio = new javax.swing.JTextField();
        txtmayorpro = new javax.swing.JTextField();
        txtnrodeestudiante = new javax.swing.JTextField();
        txtaprobados = new javax.swing.JTextField();
        txtdesaprobados = new javax.swing.JTextField();
        txtnrodesaprobados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero de orden del estudiante:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));
        getContentPane().add(txtnroestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, -1));

        jLabel2.setText("Examen 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 20));

        jLabel3.setText("Examen 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        jLabel4.setText("Examen 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));
        getContentPane().add(txtexamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, 20));
        getContentPane().add(txtexamen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, -1));
        getContentPane().add(txtexamen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, -1));

        jLabel5.setText("Promedio de aula examen 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setText("Mayor Promedio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel7.setText("Nro de estudiante");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel8.setText("Nro de aprobados");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel9.setText("Nro de desaprobados");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel10.setText("Nro de desaprobados Examen 1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));
        getContentPane().add(txtpromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 120, -1));
        getContentPane().add(txtmayorpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, -1));
        getContentPane().add(txtnrodeestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, -1));
        getContentPane().add(txtaprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 120, -1));
        getContentPane().add(txtdesaprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, -1));
        getContentPane().add(txtnrodesaprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        pos[conta]=Integer.parseInt(txtnroestudiante.getText());
        ex1[conta]=Integer.parseInt(txtexamen1.getText());
        ex2[conta]=Integer.parseInt(txtexamen2.getText());
        ex3[conta]=Integer.parseInt(txtexamen3.getText());
        conta++;
        txtnroestudiante.setText("");
        txtexamen1.setText("");
        txtexamen2.setText("");
        txtexamen3.setText("");
        txtnroestudiante.requestFocus();
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        double suma=0;
        for(int i=0;i<conta;i++){
            prom[i]=((ex1[i]+ex2[i]+ex3[i])/3);
            suma=suma+ex3[i];
        }
        
        double promex3=suma/conta;
        txtpromedio.setText(""+promex3);
        
        double mayor=0;
        for(int i=0;i<conta;i++){
            if(prom[i]>mayor){
                mayor=prom[i];
                x=i;
            }
            if(prom[i]>10.5)
                contap++;
            else
                contd++;
            if(ex1[i]<10.5)
                contex1++;
        }
        txtmayorpro.setText(""+mayor);
        txtnrodeestudiante.setText(""+pos[x]);
        txtaprobados.setText(""+contap);
        txtdesaprobados.setText(""+contd);
        txtnrodesaprobados.setText(""+contex1);
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio01().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtaprobados;
    private javax.swing.JTextField txtdesaprobados;
    private javax.swing.JTextField txtexamen1;
    private javax.swing.JTextField txtexamen2;
    private javax.swing.JTextField txtexamen3;
    private javax.swing.JTextField txtmayorpro;
    private javax.swing.JTextField txtnrodeestudiante;
    private javax.swing.JTextField txtnrodesaprobados;
    private javax.swing.JTextField txtnroestudiante;
    private javax.swing.JTextField txtpromedio;
    // End of variables declaration//GEN-END:variables
}
